// Question database organized by categories
const questionDatabase = {
	introduction: [
		{ id: 1, kinkiness: 1, spiciness: 1, question: "What's your age?" },
		{ id: 2, kinkiness: 1, spiciness: 1, question: "What genders are you into?" },
		{ id: 3, kinkiness: 1, spiciness: 1, question: "Zodiac Sign?" },
		{ id: 4, kinkiness: 1, spiciness: 1, question: "Chinese calendar animal?" },
		{ id: 5, kinkiness: 1, spiciness: 1, question: "How many languages do you know?" },
		{ id: 6, kinkiness: 1, spiciness: 1, question: "Do you have pets? How many? (Obligatory proof needed)"},
		{ id: 7, kinkiness: 1, spiciness: 1, question: "If your pet had a dating profile, what would it say?" },
		{ id: 8, kinkiness: 1, spiciness: 1, question: "What's the weirdest place you've found your pet sleeping?" },
		{ id: 9, kinkiness: 1, spiciness: 1, question: "Favorite activity?" },
		{ id: 10, kinkiness: 1, spiciness: 1, question: "Favorite snack?" },
		{ id: 11, kinkiness: 1, spiciness: 1, question: "Favorite show/film, or one you watched recently that you would recommend?" },
		{ id: 12, kinkiness: 1, spiciness: 1, question: "Top 5 songs of all times?" }, 
		{ id: 13, kinkiness: 1, spiciness: 1, question: "Top 3 hobbies?" }, 
		{ id: 14, kinkiness: 1, spiciness: 1, question: "Have you been called funny nicknames? Which?" }, 
		{ id: 15, kinkiness: 1, spiciness: 1, question: "Favorite animal/s?" }, 
		{ id: 16, kinkiness: 1, spiciness: 1, question: "Sleeping naked or not?" }, 
		{ id: 17, kinkiness: 1, spiciness: 1, question: "Pineapple on pizza or nah?" }, 
		{ id: 18, kinkiness: 1, spiciness: 1, question: "Favorite place to visit?" },
		{ id: 19, kinkiness: 1, spiciness: 1, question: "How do you organize your music playlist? By genere or by ✨vibes✨?" },
		{ id: 20, kinkiness: 1, spiciness: 1, question: "Favorite gift you ever got?" },
		{ id: 21, kinkiness: 1, spiciness: 1, question: "Favorite birthday you ever had?" },
		{ id: 22, kinkiness: 1, spiciness: 1, question: "Favorite memory?" },
		{ id: 23, kinkiness: 1, spiciness: 1, question: "Are you the kind that fidgets all the time?" },
		{ id: 24, kinkiness: 1, spiciness: 1, question: "Favorite place to visit near home?" },
		{ id: 25, kinkiness: 1, spiciness: 1, question: "Do you prefer beach or mountain vacations?" },
		{ id: 26, kinkiness: 1, spiciness: 1, question: "What's some food or weirdest combination you thought you wouldnt like that you actually did enjoy?" },
		{ id: 27, kinkiness: 1, spiciness: 1, question: "What hobby would you pick up if time and money weren't factors?" },
		{ id: 28, kinkiness: 1, spiciness: 1, question: "What hobby do you think more people should try?" },
		{ id: 29, kinkiness: 1, spiciness: 1, question: "What's your biggest technology pet peeve? (its okay to sound like a boomer from time to time)" },
		{ id: 30, kinkiness: 1, spiciness: 1, question: "How do you prefer to spend time with friends?" },
		{ id: 31, kinkiness: 1, spiciness: 1, question: "Do you belive in the supernatural? Ghosts, Vampires, etc etc" },
		{ id: 32, kinkiness: 1, spiciness: 1, question: "Do you belive in aliens? Out there, or the abducters, etc etc" },
		{ id: 33, kinkiness: 1, spiciness: 1, question: "How much wood would a woodchuck chuck if a woodchuck could chuck wood?" },
		{ id: 34, kinkiness: 1, spiciness: 1, question: "Favorite thing about where you live?" },
		{ id: 35, kinkiness: 1, spiciness: 1, question: "Where do you listen your music?" },
		{ id: 36, kinkiness: 1, spiciness: 1, question: "Do you use social media? Where are you most active?" },
		{ id: 37, kinkiness: 1, spiciness: 1, question: "How many people would you consider your real friends?" },
		{ id: 38, kinkiness: 1, spiciness: 1, question: "Are you too perfectionist, or too not-perfectionist" },
		{ id: 39, kinkiness: 1, spiciness: 1, question: "What's your most prized possession? (emotionally)" },
		{ id: 40, kinkiness: 1, spiciness: 1, question: "If you could live anywhere, where would it be? City or Town? Mountains or Beach?" },
		
		{ id: 41, kinkiness: 1, spiciness: 2, question: "Have you ever had a travel/long distance romance?" },
		{ id: 42, kinkiness: 1, spiciness: 2, question: "What's the most illegal thing you've accidentally (or not) done?" },
		{ id: 43, kinkiness: 1, spiciness: 2, question: "Have you ever been in serious danger?" },
		{ id: 44, kinkiness: 1, spiciness: 2, question: "Ever stole food from a roomate, colleague or cowerker?" },
		{ id: 45, kinkiness: 1, spiciness: 2, question: "What hobby have you kept secret because it's embarrassing?" },
		{ id: 46, kinkiness: 1, spiciness: 2, question: "What's the most obsessive you've ever been about a hobby?" },
		{ id: 47, kinkiness: 1, spiciness: 2, question: "What's in your browser history that you hope no one ever sees? (porn doesnt count)" },
		{ id: 48, kinkiness: 1, spiciness: 2, question: "What's the most addicted you've ever been to a piece of technology?" },
		{ id: 49, kinkiness: 1, spiciness: 2, question: "What's the most awkward dating experience you've had?" },
		{ id: 50, kinkiness: 1, spiciness: 2, question: "What's a relationship red flag you ignored? (friendship is a relationship too silly)" },
		{ id: 51, kinkiness: 1, spiciness: 2, question: "Ever been on a date or had a partner?" },
		{ id: 52, kinkiness: 1, spiciness: 2, question: "What's the biggest lie you've told in a relationship?" },
		{ id: 53, kinkiness: 1, spiciness: 2, question: "What's your Soma? (Your happy pill from \"Brave New World\" (Your addiction)) " },
		{ id: 54, kinkiness: 1, spiciness: 2, question: "Have you tried drugs? What's the best and worst ones you tried?" },
		{ id: 55, kinkiness: 1, spiciness: 2, question: "Ever got in a serious fight?" },
		{ id: 56, kinkiness: 1, spiciness: 2, question: "Do you pull all-nighters? How often?" },
		{ id: 57, kinkiness: 1, spiciness: 2, question: "What's the most fun event you've ever been to? Concert, Theater, Sports, etc" },
		{ id: 58, kinkiness: 1, spiciness: 2, question: "What's your most embarassing possession?" },
		{ id: 59, kinkiness: 1, spiciness: 2, question: "What's your most technologically advanced possession?" },
		{ id: 60, kinkiness: 1, spiciness: 2, question: "What's your weirdest possession?" },
		{ id: 61, kinkiness: 1, spiciness: 2, question: "What's your most technologically advanced possession?" },
		{ id: 62, kinkiness: 1, spiciness: 2, question: "Wild card question. Now you get to make the question, but non-sexual" },
		{ id: 63, kinkiness: 1, spiciness: 2, question: "Which animal represents you best Non-sexually? (shu horny puppies, that's for later)" },
		
		{ id: 64, kinkiness: 3, spiciness: 4, question: "Ever tried hypnosis? The real kind I mean. What's your thoughts on it?" },
		{ id: 65, kinkiness: 1, spiciness: 3, question: "How sure of your own gender identity are you?" },
	],
	lusty: [
		{ id: 66, kinkiness: 1, spiciness: 2, question: "When are you more likely to go \"Awhooooooooga\"? Looking at feminine lasses or masculine lads?" },
		{ id: 67, kinkiness: 1, spiciness: 2, question: "Favorite body part (not genitals), and why?" },
		{ id: 68, kinkiness: 1, spiciness: 2, question: "How possessive are you? How much would you love/hate if someone was posessive of you?" },
		{ id: 69, kinkiness: 1, spiciness: 2, question: "Virgin? One timer? The sluttiest of them all? (We love you all regardless <3)" },
		{ id: 70, kinkiness: 1, spiciness: 4, question: "I mean of course this was a question, do you love 69 or are you a pussy?" },
		{ id: 71, kinkiness: 1, spiciness: 2, question: "" },
		{ id: 72, kinkiness: 1, spiciness: 2, question: "Have you ever been seen naked by someone not blood related?" },
		{ id: 73, kinkiness: 1, spiciness: 2, question: "Do you have sex toys? (What about non-sex toys?)" },
		{ id: 74, kinkiness: 1, spiciness: 2, question: "Do you use lube? How much do you have right now?~" },
		{ id: 75, kinkiness: 1, spiciness: 2, question: "From 1 to 10, how horny are you right now?" },
		{ id: 76, kinkiness: 1, spiciness: 2, question: "Ever sexted before? Roleplay/fantasy or real sexting?" },
		{ id: 77, kinkiness: 1, spiciness: 2, question: "Which animal represents you best sexually? (its sexual behaviour, the way they procreate, etc)" },
		
		{ id: 78, kinkiness: 1, spiciness: 3, question: "" },
		{ id: 79, kinkiness: 1, spiciness: 3, question: "" },
		{ id: 80, kinkiness: 1, spiciness: 3, question: "" },
		{ id: 81, kinkiness: 1, spiciness: 3, question: "Gentle vs harsh treatmet in bed? (For this question you can only choose one >:3)" },
		{ id: 82, kinkiness: 1, spiciness: 3, question: "Fav sex toy? Do you have one, or do you wish you had it? How often do you use it/would use it?" },
		{ id: 83, kinkiness: 1, spiciness: 3, question: "Do you watch porn? If so, Favorite tag?" },
		{ id: 84, kinkiness: 1, spiciness: 3, question: "Real porn vs Hentai vs 3D?" },
		{ id: 85, kinkiness: 1, spiciness: 3, question: "What underwear are yo ucurrently wearing?~~" },            
		{ id: 86, kinkiness: 1, spiciness: 3, question: "Last time you were horny? How long ago?~" },
		{ id: 87, kinkiness: 1, spiciness: 3, question: "What non-sexual thing never fails to get you horny?" },
		{ id: 88, kinkiness: 1, spiciness: 3, question: "When have you been the horniest ever?" },
		{ id: 89, kinkiness: 1, spiciness: 3, question: "Have you ever sent nudes? With face or without?" },
		{ id: 90, kinkiness: 1, spiciness: 3, question: "Have you ever received nudes? (that you asked for)" },
		{ id: 91, kinkiness: 1, spiciness: 3, question: "Favorite (horny) superpower, and why?" },
		{ id: 92, kinkiness: 1, spiciness: 3, question: "Most embarassing sexual story?" },
		{ id: 93, kinkiness: 1, spiciness: 3, question: "Can you remember your strongest orgasm ever? (Tell us, tell us, tell us, tell-)" },
		{ id: 94, kinkiness: 1, spiciness: 3, question: "Protected or un-protected sex?" },
		{ id: 95, kinkiness: 1, spiciness: 3, question: "Ever played a strip game?" },
		{ id: 96, kinkiness: 1, spiciness: 3, question: "What's the maximum number of people you would have sex with at the same time?" },
		{ id: 97, kinkiness: 1, spiciness: 3, question: "" },
		{ id: 98, kinkiness: 1, spiciness: 3, question: "" },
		{ id: 99, kinkiness: 1, spiciness: 3, question: "" },
		{ id: 100, kinkiness: 1, spiciness: 3, question: "" },
		
		{ id: 101, kinkiness: 1, spiciness: 4, question: "Wild card question. Now you get to make the question, and very sexual~" },
		{ id: 102, kinkiness: 1, spiciness: 4, question: "How often do you have sex?" },
		{ id: 103, kinkiness: 1, spiciness: 4, question: "Fav sex position?" },
		{ id: 104, kinkiness: 2, spiciness: 4, question: "Ever masturbated in public? (sneakily or not)" },
		{ id: 105, kinkiness: 1, spiciness: 4, question: "Ever fingered your backdoor?" },
		{ id: 106, kinkiness: 1, spiciness: 4, question: "Ever given a sucky sucky? Ever polished the pole? Ever gargled the gherkin? Ever used your moist harmonica?" },
		{ id: 107, kinkiness: 1, spiciness: 4, question: "Ever gave a handy? Ever played with someone's flesh joysticking? Ever gave a meat maraca shaking?" },
		{ id: 108, kinkiness: 1, spiciness: 4, question: "Ever fingered someone? If so, both holes, or only one?" },
		{ id: 109, kinkiness: 1, spiciness: 4, question: "Thoughts on anal? Had an experience yet?" },
		{ id: 110, kinkiness: 2, spiciness: 4, question: "What about pegging, hm? Ever got Pogo-sticked? Ever done some butt jousting?" },
		{ id: 111, kinkiness: 1, spiciness: 4, question: "Ever had hot steamy same sex experience?" },
		{ id: 112, kinkiness: 2, spiciness: 4, question: "Ever given a rimjob, ever kissen the brown flower? What about receiving one?" },
		{ id: 113, kinkiness: 1, spiciness: 4, question: "Ever had sex in public? (Balcony, behind some bushes, bathroom, etc etc)" },
		{ id: 114, kinkiness: 1, spiciness: 4, question: "How do you masturbate? (Go in as much detail as scientifically possible)" },
		{ id: 115, kinkiness: 1, spiciness: 4, question: "How often do you masturbate? And what's the maximum amount of times you have masturbated in one single day?" },
		{ id: 116, kinkiness: 1, spiciness: 4, question: "Have you ever been caught masturbating?" },
		{ id: 117, kinkiness: 1, spiciness: 4, question: "Ever streamed/recorded yourself masturbating for someone else to see?" },
		{ id: 118, kinkiness: 1, spiciness: 4, question: "" },
		{ id: 119, kinkiness: 1, spiciness: 4, question: "How turned on are you by cum alone? Like not even where it comes from, just the fluid, it's stickiness, it's heat, it's.. yumminess?" },

		
		{ id: 147, kinkiness: 2, spiciness: 4, question: "Which do you think tastes better, estrogen pills or testosterone pills?" },
		{ id: 148, kinkiness: 2, spiciness: 4, question: "Thoughts about furry stuff? Into it? Against it? Or just dont care?" },
		{ id: 149, kinkiness: 2, spiciness: 4, question: "What about natural body musk? Are you into it? If so, what part of the body smells the best? The most potent and alluring?" },
		{ id: 150, kinkiness: 3, spiciness: 4, question: "Thoughts about pet play? Would you be a pet or an owner/caretaker?" },
		{ id: 151, kinkiness: 2, spiciness: 4, question: "" },
		{ id: 152, kinkiness: 3, spiciness: 4, question: "Thoughts about chastity? Would you lock yourself for someone?" },
		{ id: 153, kinkiness: 3, spiciness: 4, question: "Would you keep someone under chastity? Keep their keys, tease them incesantly, knowing they cannot release themselves without your say so?" },
		{ id: 154, kinkiness: 3, spiciness: 4, question: "Thoughts about sissy/beta male stuff? Is it hot? Is it not? Is just just a way to cope with trans thoughts / bisexaulity? Or just a thing of it's own?" },
		
		{ id: 175, kinkiness: 4, spiciness: 4, question: "What about mind control? Would you love having your thoughts controlled without a way to resist? What about the opposite? What would you do if you could control someone's body with your words alone?" },
		{ id: 176, kinkiness: 4, spiciness: 4, question: "Ever tried erotic hypnosis? The real kind I mean" },
		
		
	],
	bdsm: [
		{ id: 201, kinkiness: 2, spiciness: 4, question: "Ever been in a serious Dom/sub relationship?" },
		{ id: 202, kinkiness: 2, spiciness: 4, question: "Sub? Dom? Switch leaning sub? Switch leaning dom? The rarest breed of actually full switch (and not pretending to be a switch when in reality you are leaning sub)?" },
		{ id: 203, kinkiness: 2, spiciness: 4, question: "Did you try being a sub? What about a dom?" },
		{ id: 204, kinkiness: 2, spiciness: 4, question: "Thoughts on role reversal? The always confident dom becoming a pathetic little nervous wreck, while the always subby takes control, does that sound fun?~~" },
		
		{ id: 210, kinkiness: 3, spiciness: 4, question: "Thougts on tasks? Do you like giving/receiving tasks to complete for the dom, or do you find they end up becoming tedious?" },
		
		{ id: 230, kinkiness: 4, spiciness: 4, question: "Thoughts on light CBT? Does lightly slapping someone's balls and watching as they shiver in pain and pleasure sound hot?" },
		{ id: 231, kinkiness: 4, spiciness: 4, question: "Thoughts on hard CBT? Does stepping on someone's cock or kicking their balls and watching as they cum from that alone sound hot?" },
		
	],
	couple: [
		{ id: 241, kinkiness: 1, spiciness: 2, question: "What's your favorite thing about your partner? What about the least favorite?" },
		{ id: 242, kinkiness: 1, spiciness: 2, question: "What's your partner's favorite body part?" },
		
		{ id: 243, kinkiness: 1, spiciness: 3, question: "Is there something your partner does which turns you on, and you think they are unaware of the fact yet?" },	
		
		{ id: 244, kinkiness: 1, spiciness: 4, question: "What's the hottest thing you've done with your parther?" },		
		
	],
	banana: [
		{ id: 281, kinkiness: 1, spiciness: 2, question: "Ever got yourself a sucked off?" },
		{ id: 282, kinkiness: 1, spiciness: 2, question: "Ever got a handjob?" },
		
		{ id: 283, kinkiness: 1, spiciness: 3, question: "" },		
		
		{ id: 300, kinkiness: 4, spiciness: 4, question: "Thoughts on light CBT? Does being spanked with the inclusion of your testies, or being told to slap your testies with a dildo until you cum sound hot?" },
		
		
	],
	shell: [
		{ id: 321, kinkiness: 1, spiciness: 2, question: "Ever got eaten out?" },
		{ id: 322, kinkiness: 1, spiciness: 2, question: "Ever got fingered?" },
		
		{ id: 323, kinkiness: 1, spiciness: 3, question: "What's the biggest thing you inserted before?" },		
		{ id: 324, kinkiness: 1, spiciness: 3, question: "" },		
		

		
	],
	petplay: [
		{ id: 361, kinkiness: 3, spiciness: 3, question: "Which are more dominant: Puppy boys/girl or Kitty boys/girls?" },
		{ id: 362, kinkiness: 3, spiciness: 3, question: "What's your favorite trick?" },
		
		{ id: 370, kinkiness: 3, spiciness: 4, question: "Thoughts on clicker training? Ever tried?" },
		{ id: 371, kinkiness: 3, spiciness: 4, question: "Does making someone sleep in a dog crate sound hot? What about you sleeping in one? (be honest)" },
		{ id: 372, kinkiness: 3, spiciness: 4, question: "Did you know that its imposible to pronounce \"rough\" with your tongue out?" },
		
	],
	wouldyourather: [
		{ id: 400, kinkiness: 1, spiciness: 2, question: "" },
		{ id: 401, kinkiness: 1, spiciness: 2, question: "" },
		
		{ id: 421, kinkiness: 1, spiciness: 3, question: "" },		
		
		{ id: 441, kinkiness: 1, spiciness: 4, question: "Would you rather have a succubuss tatto so that your sexual partner feels all that you feel, OR, so that you can feel all that they feel?" },		
		
		{ id: 461, kinkiness: 1, spiciness: 5, question: "Would you rather have hot steaming sexting rn, OR.. there is no or" },		
		{ id: 462, kinkiness: 1, spiciness: 5, question: "" },		
		
	],
};