// Question database organized by categories
const questionDatabase = {
	introduction: [
		{ id: 1, kinkiness: 1, spiciness: 1, question: "What's your age?" },
		{ id: 2, kinkiness: 1, spiciness: 1, question: "What genders are you into?" },
		{ id: 3, kinkiness: 1, spiciness: 1, question: "Zodiac Sign?" },
		{ id: 4, kinkiness: 1, spiciness: 1, question: "Chinese calendar animal?" },
		{ id: 5, kinkiness: 1, spiciness: 1, question: "How many languages do you know?" },
		{ id: 6, kinkiness: 1, spiciness: 1, question: "Do you have pets? How many? (Obligatory proof needed)"},
		{ id: 7, kinkiness: 1, spiciness: 1, question: "If your pet had a dating profile, what would it say?" },
		{ id: 8, kinkiness: 1, spiciness: 1, question: "What's the weirdest place you've found your pet sleeping?" },
		{ id: 9, kinkiness: 1, spiciness: 1, question: "Favorite activity?" },
		{ id: 10, kinkiness: 1, spiciness: 1, question: "Favorite snack?" },
		{ id: 11, kinkiness: 1, spiciness: 1, question: "Favorite show/film, or one you watched recently that you would recommend?" },
		{ id: 12, kinkiness: 1, spiciness: 1, question: "Top 5 songs of all times?" }, 
		{ id: 13, kinkiness: 1, spiciness: 1, question: "Top 3 hobbies?" }, 
		{ id: 14, kinkiness: 1, spiciness: 1, question: "Have you been called funny nicknames? Which?" }, 
		{ id: 15, kinkiness: 1, spiciness: 1, question: "Favorite animal/s?" }, 
		{ id: 16, kinkiness: 1, spiciness: 1, question: "Sleeping naked or not?" }, 
		{ id: 17, kinkiness: 1, spiciness: 1, question: "Pineapple on pizza or nah?" }, 
		{ id: 18, kinkiness: 1, spiciness: 1, question: "Favorite place to visit?" },
		{ id: 19, kinkiness: 1, spiciness: 1, question: "How do you organize your music playlist? By genere or by ✨vibes✨?" },
		{ id: 20, kinkiness: 1, spiciness: 1, question: "Favorite gift you ever got?" },
		{ id: 21, kinkiness: 1, spiciness: 1, question: "Favorite birtday?" },
		{ id: 22, kinkiness: 1, spiciness: 1, question: "Favorite memory?" },
		{ id: 23, kinkiness: 1, spiciness: 1, question: "Are you the kind that fidgets all the time?" },
		{ id: 24, kinkiness: 1, spiciness: 1, question: "Favorite place to visit near home?" },
		{ id: 25, kinkiness: 1, spiciness: 1, question: "Do you prefer beach or mountain vacations?" },
		{ id: 26, kinkiness: 1, spiciness: 1, question: "What's some food or weirdest combination you thought you wouldnt like that you actually did enjoy?" },
		{ id: 27, kinkiness: 1, spiciness: 1, question: "What hobby would you pick up if time and money weren't factors?" },
		{ id: 28, kinkiness: 1, spiciness: 1, question: "What hobby do you think more people should try?" },
		{ id: 29, kinkiness: 1, spiciness: 1, question: "What's your biggest technology pet peeve? (its okay to sound like a boomer from time to time)" },
		{ id: 30, kinkiness: 1, spiciness: 1, question: "How do you prefer to spend time with friends?" },
		{ id: 31, kinkiness: 1, spiciness: 1, question: "Do you belive in the supernatural? Ghosts, Vampires, etc etc" },
		{ id: 32, kinkiness: 1, spiciness: 1, question: "Do you belive in aliens? Out there, or the abducters, etc etc" },
		{ id: 33, kinkiness: 1, spiciness: 1, question: "How much wood would a woodchuck chuck if a woodchuck could chuck wood?" },
		{ id: 34, kinkiness: 1, spiciness: 1, question: "Favorite thing about where you live?" },
		{ id: 35, kinkiness: 1, spiciness: 1, question: "Where do you listen your music?" },
		{ id: 36, kinkiness: 1, spiciness: 1, question: "Do you use social media? Where are you most active?" },
		{ id: 37, kinkiness: 1, spiciness: 1, question: "How many people would you consider your real friends?" },
		{ id: 38, kinkiness: 1, spiciness: 1, question: "Are you too perfectionist, or too not-perfectionist" },
		{ id: 39, kinkiness: 1, spiciness: 1, question: "What's your most prized possession? (emotionally)" },
		{ id: 40, kinkiness: 1, spiciness: 1, question: "If you could live anywhere, where would it be? City or Town? Mountains or Beach?" },
		
		{ id: 41, kinkiness: 1, spiciness: 2, question: "Have you ever had a travel/long distance romance?" },
		{ id: 42, kinkiness: 1, spiciness: 2, question: "What's the most illegal thing you've accidentally (or not) done?" },
		{ id: 43, kinkiness: 1, spiciness: 2, question: "Have you ever been in serious danger?" },
		{ id: 44, kinkiness: 1, spiciness: 2, question: "Ever stole food from a roomate, colleague or cowerker?" },
		{ id: 45, kinkiness: 1, spiciness: 2, question: "What hobby have you kept secret because it's embarrassing?" },
		{ id: 46, kinkiness: 1, spiciness: 2, question: "What's the most obsessive you've ever been about a hobby?" },
		{ id: 47, kinkiness: 1, spiciness: 2, question: "What's in your browser history that you hope no one ever sees? (porn doesnt count)" },
		{ id: 48, kinkiness: 1, spiciness: 2, question: "What's the most addicted you've ever been to a piece of technology?" },
		{ id: 49, kinkiness: 1, spiciness: 2, question: "What's the most awkward dating experience you've had?" },
		{ id: 50, kinkiness: 1, spiciness: 2, question: "What's a relationship red flag you ignored? (friendship is a relationship too silly)" },
		{ id: 51, kinkiness: 1, spiciness: 2, question: "Ever been on a date or had a partner?" },
		{ id: 52, kinkiness: 1, spiciness: 2, question: "What's the biggest lie you've told in a relationship?" },
		{ id: 53, kinkiness: 1, spiciness: 2, question: "What's your addiction?" },
		{ id: 54, kinkiness: 1, spiciness: 2, question: "Have you tried drugs? What's the best and worst ones you tried?" },
		{ id: 55, kinkiness: 1, spiciness: 2, question: "Ever got in a searious fight?" },
		{ id: 56, kinkiness: 1, spiciness: 2, question: "Do you pull all-nighters? How often?" },
		{ id: 57, kinkiness: 1, spiciness: 2, question: "What's the most fun event you've ever been to? Concert, Theater, Sports, etc" },
		{ id: 58, kinkiness: 1, spiciness: 2, question: "What's your most embarassing possession?" },
		{ id: 59, kinkiness: 1, spiciness: 2, question: "What's your most technologically advanced possession?" },
		{ id: 60, kinkiness: 1, spiciness: 2, question: "What's your weirdest possession?" },
		{ id: 61, kinkiness: 1, spiciness: 2, question: "What's your most technologically advanced possession?" },
		{ id: 62, kinkiness: 1, spiciness: 2, question: "Wild card question. Now you get to make the question, but non-sexual" },
		{ id: 63, kinkiness: 1, spiciness: 2, question: "Which animal represents you best Non-sexually? (shu horny puppies, that's for later)" },
	],
	lusty: [
		{ id: 63, kinkiness: 1, spiciness: 2, question: "When are you more likely to go \"Awhooooooooga\"? With looking a feminine lasses or masculine lads?" },
		{ id: 64, kinkiness: 1, spiciness: 2, question: "Favorite body part (not genitals), and why?" },
		{ id: 65, kinkiness: 1, spiciness: 2, question: "How possessive are you? How much would you love/hate if someone was posessive of you?" },
		{ id: 66, kinkiness: 1, spiciness: 2, question: "Favorite (horny) superpower, and why?" },
		{ id: 67, kinkiness: 1, spiciness: 2, question: "" },
		
		{ id: 69, kinkiness: 1, spiciness: 3, question: "I mean of course this was a question, 69 or are you a pussy?" },
		{ id: 70, kinkiness: 1, spiciness: 3, question: "Gentle vs harsh treatmet in bed?" },
		{ id: 71, kinkiness: 1, spiciness: 3, question: "Fav sex toy? Do you have one?" },
		{ id: 72, kinkiness: 1, spiciness: 3, question: "Do you watch porn? If so, Favorite tag?" },
		{ id: 73, kinkiness: 1, spiciness: 3, question: "Real porn vs Hentai vs 3D?" },
		{ id: 74, kinkiness: 1, spiciness: 3, question: "Fav sex position?" },
		{ id: 74, kinkiness: 1, spiciness: 3, question: "Fav sex position?" },
		{ id: 100, kinkiness: 1, spiciness: 3, question: "Wild card question. Now you get to make the question, and very sexual~" },
		
	],
	bdsm: [
		{ id: 101, kinkiness: 2, spiciness: 2, question: "Ever been in a serious Dom/sub relationship?" },
		{ id: 102, kinkiness: 2, spiciness: 2, question: "" },
		
		{ id: 103, kinkiness: 2, spiciness: 3, question: "" },		
		
	],
	couple: [
		{ id: 141, kinkiness: 1, spiciness: 2, question: "What's your favorite thing about your partner? What about the least favorite?" },
		{ id: 142, kinkiness: 1, spiciness: 2, question: "" },
		
		{ id: 143, kinkiness: 1, spiciness: 3, question: "" },		
		
	],
	banana: [
		{ id: 181, kinkiness: 1, spiciness: 2, question: "" },
		{ id: 182, kinkiness: 1, spiciness: 2, question: "" },
		
		{ id: 183, kinkiness: 1, spiciness: 3, question: "" },		
		
	],
	shell: [
		{ id: 221, kinkiness: 1, spiciness: 2, question: "" },
		{ id: 222, kinkiness: 1, spiciness: 2, question: "" },
		
		{ id: 223, kinkiness: 1, spiciness: 3, question: "" },		
		
	],
	wouldyourather: [
		{ id: 261, kinkiness: 1, spiciness: 2, question: "" },
		{ id: 262, kinkiness: 1, spiciness: 2, question: "" },
		
		{ id: 263, kinkiness: 1, spiciness: 3, question: "" },		
		
	],
};